networks:
  db-postgres-net:
    name: db-postgres-net
    driver: bridge
services:
  postgres-service:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - db-postgres-net
    volumes:
      - /usr/lib/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  my-app-quarkus:
    image: my-app-quarkus-2
    build:
      context: .
    networks:
      - db-postgres-net
    ports:
      - "8080:8080"
    depends_on:
      - postgres-service
    restart: unless-stopped